export interface HrQuestion {
  id: string;
  module: string;
  item_code: string;
  question_text: string;
  options: { label: string; value: number }[];
  weight: number;
}

export interface HrModule {
  id: string;
  name: string;
  weight: number;
  questions: HrQuestion[];
}

export const hrModules: HrModule[] = [
  {
    id: "module_1",
    name: "HR Governance & Strategic Positioning",
    weight: 15,
    questions: [
      {
        id: "HRG1",
        module: "module_1",
        item_code: "HRG1",
        question_text: "Funcția de resurse umane este formal definită în structura organizației.",
        options: [
          { label: "Nu există responsabil clar pentru HR", value: 1 },
          { label: "Activitățile HR sunt gestionate ad-hoc de management / contabilitate / administrativ", value: 2 },
          { label: "Există persoană responsabilă, dar rolul nu este clar formalizat", value: 3 },
          { label: "Există funcție / departament HR clar definit", value: 4 },
          { label: "Funcția HR are rol strategic clar și poziționare formală în organizație", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG2",
        module: "module_1",
        item_code: "HRG2",
        question_text: "Responsabilul HR are pregătire relevantă în managementul resurselor umane.",
        options: [
          { label: "Fără pregătire specifică HR", value: 1 },
          { label: "Cunoștințe dobândite informal", value: 2 },
          { label: "Cursuri punctuale / experiență practică", value: 3 },
          { label: "Formare profesională relevantă în HR", value: 4 },
          { label: "Certificări / dezvoltare continuă / expertiză avansată", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG3",
        module: "module_1",
        item_code: "HRG3",
        question_text: "Top management implică funcția HR în deciziile care afectează personalul și organizația.",
        options: [
          { label: "HR nu este consultat", value: 1 },
          { label: "HR este consultat doar administrativ", value: 2 },
          { label: "HR este consultat uneori", value: 3 },
          { label: "HR participă regulat la decizii relevante", value: 4 },
          { label: "HR este partener strategic în procesul decizional", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG4",
        module: "module_1",
        item_code: "HRG4",
        question_text: "Managerii de departamente colaborează activ cu HR în probleme legate de oameni.",
        options: [
          { label: "Aproape deloc", value: 1 },
          { label: "Doar când apar probleme urgente", value: 2 },
          { label: "Colaborare ocazională", value: 3 },
          { label: "Colaborare regulată", value: 4 },
          { label: "Colaborare structurată și predictibilă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG5",
        module: "module_1",
        item_code: "HRG5",
        question_text: "Propunerile formulate de HR sunt aprobate și implementate de management.",
        options: [
          { label: "Aproape niciodată", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Aproape întotdeauna", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG6",
        module: "module_1",
        item_code: "HRG6",
        question_text: "Organizația are politici și proceduri HR documentate (recrutare, evaluare, concedii, disciplină etc.).",
        options: [
          { label: "Nu există documentație", value: 1 },
          { label: "Există reguli informale", value: 2 },
          { label: "Există proceduri pentru unele procese", value: 3 },
          { label: "Majoritatea proceselor sunt documentate", value: 4 },
          { label: "Procedurile sunt complete, actualizate și utilizate constant", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG7",
        module: "module_1",
        item_code: "HRG7",
        question_text: "Procesele HR sunt aplicate consecvent, indiferent de manager sau departament.",
        options: [
          { label: "Fiecare procedează diferit", value: 1 },
          { label: "Există variații mari", value: 2 },
          { label: "Aplicare relativ consecventă", value: 3 },
          { label: "Aplicare standard în majoritatea cazurilor", value: 4 },
          { label: "Aplicare uniformă și auditabilă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG8",
        module: "module_1",
        item_code: "HRG8",
        question_text: "Există indicatori HR monitorizați periodic (ex: fluctuație, absenteism, time-to-hire, training hours, engagement).",
        options: [
          { label: "Nu monitorizăm indicatori", value: 1 },
          { label: "Ocazional, punctual", value: 2 },
          { label: "Monitorizăm câțiva indicatori de bază", value: 3 },
          { label: "Monitorizare periodică structurată", value: 4 },
          { label: "Dashboard HR cu analiză și decizii bazate pe date", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG9",
        module: "module_1",
        item_code: "HRG9",
        question_text: "Există obiective HR definite anual și corelate cu obiectivele companiei.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Priorități informale", value: 2 },
          { label: "Obiective parțial definite", value: 3 },
          { label: "Plan anual clar", value: 4 },
          { label: "Plan strategic monitorizat prin KPI", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG10",
        module: "module_1",
        item_code: "HRG10",
        question_text: "Organizația planifică inițiative HR proactive, nu doar reacționează la probleme.",
        options: [
          { label: "Exclusiv reactiv", value: 1 },
          { label: "Mai ales reactiv", value: 2 },
          { label: "Mixt", value: 3 },
          { label: "Predominant planificat", value: 4 },
          { label: "Management anticipativ bazat pe analiză", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG11",
        module: "module_1",
        item_code: "HRG11",
        question_text: "HR are buget dedicat pentru inițiative specifice (training, recrutare, wellbeing, employer branding etc.).",
        options: [
          { label: "Fără buget", value: 1 },
          { label: "Aprobare punctuală doar la nevoie", value: 2 },
          { label: "Buget limitat informal", value: 3 },
          { label: "Buget anual definit", value: 4 },
          { label: "Buget strategic planificat și urmărit", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG12",
        module: "module_1",
        item_code: "HRG12",
        question_text: "Valorile și cultura organizațională sunt clar comunicate angajaților.",
        options: [
          { label: "Nu sunt definite", value: 1 },
          { label: "Există informal", value: 2 },
          { label: "Sunt comunicate parțial", value: 3 },
          { label: "Sunt clar definite și comunicate", value: 4 },
          { label: "Sunt integrate activ în management și comportamente", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "HRG13",
        module: "module_1",
        item_code: "HRG13",
        question_text: "Organizația tratează angajații ca resursă strategică, nu exclusiv ca resursă operațională.",
        options: [
          { label: "Accent exclusiv pe execuție", value: 1 },
          { label: "Accent preponderent operațional", value: 2 },
          { label: "Abordare mixtă", value: 3 },
          { label: "Oamenii sunt considerați activ strategic", value: 4 },
          { label: "People-first culture demonstrabilă", value: 5 },
        ],
        weight: 1,
      },
    ],
  },
  {
    id: "module_2",
    name: "Planificarea Resurselor Umane / Workforce Planning",
    weight: 10,
    questions: [
      {
        id: "WFP1",
        module: "module_2",
        item_code: "WFP1",
        question_text: "Necesarul de personal este estimat anticipat, pe baza volumului de activitate sau planurilor de business.",
        options: [
          { label: "Doar când apare urgența", value: 1 },
          { label: "Ocazional", value: 2 },
          { label: "Pentru anumite zone", value: 3 },
          { label: "Sistematic anual", value: 4 },
          { label: "Forecast periodic și scenarii", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP2",
        module: "module_2",
        item_code: "WFP2",
        question_text: "Există planuri de recrutare bazate pe necesar estimat, nu doar pe posturi vacante apărute.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Exclusiv reactiv", value: 2 },
          { label: "Parțial planificat", value: 3 },
          { label: "Planificare anuală", value: 4 },
          { label: "Planificare predictivă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP3",
        module: "module_2",
        item_code: "WFP3",
        question_text: "Organizația monitorizează fluctuația de personal și impactul acesteia.",
        options: [
          { label: "Nu monitorizăm", value: 1 },
          { label: "Observăm informal", value: 2 },
          { label: "Evidență de bază", value: 3 },
          { label: "Monitorizare periodică", value: 4 },
          { label: "Analiză + măsuri preventive", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP4",
        module: "module_2",
        item_code: "WFP4",
        question_text: "Există o evidență actualizată a competențelor profesionale ale angajaților.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Informații dispersate", value: 2 },
          { label: "Evidență parțială", value: 3 },
          { label: "Evidență structurată", value: 4 },
          { label: "Skill matrix actualizat periodic", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP5",
        module: "module_2",
        item_code: "WFP5",
        question_text: "Organizația identifică competențele critice necesare pentru viitor.",
        options: [
          { label: "Nu analizăm", value: 1 },
          { label: "Doar intuitiv", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Analiză structurată", value: 4 },
          { label: "Strategic workforce capability planning", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP6",
        module: "module_2",
        item_code: "WFP6",
        question_text: "Distribuția personalului pe roluri este evaluată periodic pentru eficiență operațională.",
        options: [
          { label: "Niciodată", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Sistematic pe bază de indicatori", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP7",
        module: "module_2",
        item_code: "WFP7",
        question_text: "Există identificare a pozițiilor-cheie care ar genera risc dacă devin vacante.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Informal", value: 2 },
          { label: "Parțial", value: 3 },
          { label: "Formalizat", value: 4 },
          { label: "Cu planuri de continuitate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP8",
        module: "module_2",
        item_code: "WFP8",
        question_text: "Există soluții pentru succesiune internă pe roluri critice.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Reacție punctuală", value: 2 },
          { label: "Pentru unele poziții", value: 3 },
          { label: "Proces formal", value: 4 },
          { label: "Succession planning matur", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP9",
        module: "module_2",
        item_code: "WFP9",
        question_text: "Mobilitatea internă este utilizată ca soluție pentru acoperirea nevoilor de personal.",
        options: [
          { label: "Niciodată", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Politică structurată de internal mobility", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP10",
        module: "module_2",
        item_code: "WFP10",
        question_text: "Datele despre angajați sunt centralizate și ușor accesibile pentru decizii HR.",
        options: [
          { label: "Exclusiv manual / dispersate", value: 1 },
          { label: "Parțial centralizate", value: 2 },
          { label: "Organizare de bază", value: 3 },
          { label: "Centralizare bună", value: 4 },
          { label: "HR data management matur", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "WFP11",
        module: "module_2",
        item_code: "WFP11",
        question_text: "Organizația utilizează date HR pentru planificarea deciziilor privind personalul.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Decizii sunt bazate pe analiză de date (data analytics)", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_3",
    name: "Recrutare și Selecție / Recruitment & Selection",
    weight: 15,
    questions: [
      {
        id: "REC1",
        module: "module_3",
        item_code: "REC1",
        question_text: "Organizația are fișe de post actualizate pentru pozițiile existente.",
        options: [
          { label: "Nu există fișe de post", value: 1 },
          { label: "Există pentru unele poziții, dar sunt depășite", value: 2 },
          { label: "Există pentru majoritatea pozițiilor, cu actualizare ocazională", value: 3 },
          { label: "Sunt actualizate periodic și utilizate în procesele HR", value: 4 },
          { label: "Sunt integrate în recrutare, evaluare și dezvoltare", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC2",
        module: "module_3",
        item_code: "REC2",
        question_text: "Profilul candidatului ideal (competențe, experiență, comportamente) este clar definit înainte de recrutare.",
        options: [
          { label: "Nu este definit", value: 1 },
          { label: "Este stabilit informal, intuitiv", value: 2 },
          { label: "Este definit pentru unele recrutări", value: 3 },
          { label: "Este definit sistematic înaintea recrutării", value: 4 },
          { label: "Există profiluri standardizate și validate împreună cu managerii", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC3",
        module: "module_3",
        item_code: "REC3",
        question_text: "Necesarul de recrutare este planificat anticipat, nu doar ca reacție la plecări sau urgențe.",
        options: [
          { label: "Exclusiv reactiv", value: 1 },
          { label: "Predominant reactiv", value: 2 },
          { label: "Uneori planificat", value: 3 },
          { label: "Majoritar planificat", value: 4 },
          { label: "Planificare predictivă bazată pe business forecast", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC4",
        module: "module_3",
        item_code: "REC4",
        question_text: "Organizația utilizează activ canale multiple pentru atragerea candidaților (ex: LinkedIn, Facebook, site propriu).",
        options: [
          { label: "1 canal ocazional", value: 1 },
          { label: "1–2 canale utilizate limitat", value: 2 },
          { label: "2–3 canale recurente", value: 3 },
          { label: "Minimum 4 canale active", value: 4 },
          { label: "Strategie multi-channel monitorizată prin rezultate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC5",
        module: "module_3",
        item_code: "REC5",
        question_text: "Organizația utilizează programe de recomandare internă (employee referral) pentru recrutare.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Program formal cu monitorizare rezultate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC6",
        module: "module_3",
        item_code: "REC6",
        question_text: "Organizația desfășoară activități de employer branding pentru atragerea candidaților.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Acțiuni ocazionale", value: 2 },
          { label: "1–2 inițiative recurente", value: 3 },
          { label: "Minimum 3 acțiuni recurente", value: 4 },
          { label: "Strategie formală cu indicatori de impact", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC7",
        module: "module_3",
        item_code: "REC7",
        question_text: "Procesul de recrutare urmează pași standard definiți și documentați.",
        options: [
          { label: "Nu există proces standard", value: 1 },
          { label: "Depinde de manager / caz", value: 2 },
          { label: "Există practici parțiale", value: 3 },
          { label: "Proces standard aplicat consecvent", value: 4 },
          { label: "Proces standard monitorizat și optimizat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC8",
        module: "module_3",
        item_code: "REC8",
        question_text: "Responsabilitățile între HR și managerii operaționali în recrutare sunt clar definite.",
        options: [
          { label: "Nu sunt clare", value: 1 },
          { label: "Frecvent confuze", value: 2 },
          { label: "Claritate parțială", value: 3 },
          { label: "Clar definite", value: 4 },
          { label: "Clar definite și aplicate consecvent", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC9",
        module: "module_3",
        item_code: "REC9",
        question_text: "Durata procesului de recrutare (time-to-hire) este monitorizată.",
        options: [
          { label: "Nu se măsoară", value: 1 },
          { label: "Estimări informale", value: 2 },
          { label: "Monitorizare ocazională", value: 3 },
          { label: "Monitorizare periodică", value: 4 },
          { label: "KPI activ utilizat pentru optimizare", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC10",
        module: "module_3",
        item_code: "REC10",
        question_text: "Organizația utilizează criterii standard de selecție definite înainte de evaluarea candidaților.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Criterii intuitive", value: 2 },
          { label: "Criterii pentru unele recrutări", value: 3 },
          { label: "Criterii standard aplicate constant", value: 4 },
          { label: "Criterii calibrate și revizuite periodic", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC11",
        module: "module_3",
        item_code: "REC11",
        question_text: "Interviurile de selecție utilizează ghiduri sau structuri standardizate.",
        options: [
          { label: "Interviuri complet nestructurate", value: 1 },
          { label: "Depinde de intervievator", value: 2 },
          { label: "Structură parțială", value: 3 },
          { label: "Ghid standard aplicat constant", value: 4 },
          { label: "Interviuri calibrate și evaluate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC12",
        module: "module_3",
        item_code: "REC12",
        question_text: "Organizația utilizează instrumente suplimentare de evaluare a candidaților (teste, studii de caz).",
        options: [
          { label: "Nu utilizăm", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Pentru anumite roluri", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic, în funcție de profilul postului", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC13",
        module: "module_3",
        item_code: "REC13",
        question_text: "Deciziile de selecție sunt luate pe baza unor criterii obiective și documentate.",
        options: [
          { label: "Predominant subiectiv", value: 1 },
          { label: "Mai degrabă intuitiv", value: 2 },
          { label: "Mixt", value: 3 },
          { label: "Predominant obiectiv", value: 4 },
          { label: "Complet documentat și auditabil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC14",
        module: "module_3",
        item_code: "REC14",
        question_text: "Candidații primesc comunicare clară și feedback privind procesul de recrutare.",
        options: [
          { label: "Aproape niciodată", value: 1 },
          { label: "Doar uneori", value: 2 },
          { label: "Comunicarea este inconsistentă", value: 3 },
          { label: "Feedback oferit în majoritatea cazurilor", value: 4 },
          { label: "Candidate communication standardizată și monitorizată", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC15",
        module: "module_3",
        item_code: "REC15",
        question_text: "Experiența candidaților în procesul de recrutare este evaluată.",
        options: [
          { label: "Nu evaluăm", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Sistematic + măsuri de îmbunătățire", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "REC16",
        module: "module_3",
        item_code: "REC16",
        question_text: "Există un proces formal de transfer de la recrutare la onboarding.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Transfer informal", value: 2 },
          { label: "Parțial structurat", value: 3 },
          { label: "Proces clar definit", value: 4 },
          { label: "Proces integrat și monitorizat", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_4",
    name: "Managementul Performanței, Motivație și Recompense",
    weight: 20,
    questions: [
      {
        id: "PER1",
        module: "module_4",
        item_code: "PER1",
        question_text: "Organizația utilizează un proces formal de evaluare a performanței angajaților.",
        options: [
          { label: "Nu există evaluare formală", value: 1 },
          { label: "Evaluare ocazională / informală", value: 2 },
          { label: "Aplicată doar anumitor categorii", value: 3 },
          { label: "Aplicată constant pentru majoritatea angajaților", value: 4 },
          { label: "Proces formal complet, documentat și revizuit periodic", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER2",
        module: "module_4",
        item_code: "PER2",
        question_text: "Fiecare angajat are obiective clare de performanță definite.",
        options: [
          { label: "Nu există obiective clare", value: 1 },
          { label: "Obiective stabilite informal", value: 2 },
          { label: "Obiective doar pentru anumite roluri", value: 3 },
          { label: "Obiective clare pentru majoritatea angajaților", value: 4 },
          { label: "Obiective standardizate și corelate cu business goals", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER3",
        module: "module_4",
        item_code: "PER3",
        question_text: "Obiectivele individuale sunt măsurabile și evaluabile (ex. KPI).",
        options: [
          { label: "Nu sunt măsurabile", value: 1 },
          { label: "Rareori măsurabile", value: 2 },
          { label: "Parțial măsurabile", value: 3 },
          { label: "Majoritar măsurabile", value: 4 },
          { label: "Complet definite prin indicatori", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER4",
        module: "module_4",
        item_code: "PER4",
        question_text: "Performanța este evaluată pe baza unor criterii cunoscute anticipat de angajați.",
        options: [
          { label: "Nu există criterii clare", value: 1 },
          { label: "Criterii comunicate inconsistent", value: 2 },
          { label: "Claritate parțială", value: 3 },
          { label: "Criterii clare și comunicate", value: 4 },
          { label: "Criterii transparente și formal documentate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER5",
        module: "module_4",
        item_code: "PER5",
        question_text: "Procesul de evaluare este aplicat consecvent între departamente și manageri.",
        options: [
          { label: "Fiecare manager procedează diferit", value: 1 },
          { label: "Diferențe mari între departamente", value: 2 },
          { label: "Aplicare relativ uniformă", value: 3 },
          { label: "Proces standard aplicat consistent", value: 4 },
          { label: "Proces calibrat și auditabil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER6",
        module: "module_4",
        item_code: "PER6",
        question_text: "Managerii oferă feedback structurat privind performanța angajaților.",
        options: [
          { label: "Doar când apar probleme", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Feedback continuu și structurată", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER7",
        module: "module_4",
        item_code: "PER7",
        question_text: "Există întâlniri periodice dedicate discuțiilor despre performanță și dezvoltare.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Parte integrată din cultura managerială", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER8",
        module: "module_4",
        item_code: "PER8",
        question_text: "Rezultatele evaluării performanței conduc la acțiuni concrete (coaching, promovare).",
        options: [
          { label: "Nu generează acțiuni", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic și documentat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER9",
        module: "module_4",
        item_code: "PER9",
        question_text: "Organizația utilizează criterii clare pentru acordarea recompenselor financiare.",
        options: [
          { label: "Nu există criterii clare", value: 1 },
          { label: "Decizii predominant subiective", value: 2 },
          { label: "Criterii parțial definite", value: 3 },
          { label: "Criterii clare și aplicate", value: 4 },
          { label: "Sistem transparent și predictibil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER10",
        module: "module_4",
        item_code: "PER10",
        question_text: "Performanța influențează direct recompensarea financiară.",
        options: [
          { label: "Nu influențează", value: 1 },
          { label: "Foarte puțin", value: 2 },
          { label: "Influență moderată", value: 3 },
          { label: "Influență clară", value: 4 },
          { label: "Corelare formală și consistentă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER11",
        module: "module_4",
        item_code: "PER11",
        question_text: "Organizația utilizează forme variabile de recompensare (bonusuri, incentive).",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Limitat", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistem formal de reward management", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER12",
        module: "module_4",
        item_code: "PER12",
        question_text: "Politica salarială este percepută ca echitabilă intern.",
        options: [
          { label: "Percepție puternic negativă", value: 1 },
          { label: "Frecvente nemulțumiri", value: 2 },
          { label: "Percepție mixtă", value: 3 },
          { label: "Majoritar pozitivă", value: 4 },
          { label: "Echitate monitorizată activ", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER13",
        module: "module_4",
        item_code: "PER13",
        question_text: "Nivelul salarial este competitiv față de piața relevantă.",
        options: [
          { label: "Mult sub piață", value: 1 },
          { label: "Sub piață", value: 2 },
          { label: "Aproximativ comparabil", value: 3 },
          { label: "Competitiv", value: 4 },
          { label: "Benchmark salarial activ", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER14",
        module: "module_4",
        item_code: "PER14",
        question_text: "Organizația utilizează forme non-financiare de motivare (apreciere, beneficii).",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Inițiative punctuale", value: 3 },
          { label: "Practici recurente", value: 4 },
          { label: "Strategie coerentă de motivare non-financiară", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER15",
        module: "module_4",
        item_code: "PER15",
        question_text: "Performerii sunt recunoscuți vizibil în organizație.",
        options: [
          { label: "Nu există recunoaștere formală", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Program formal de recognition", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER16",
        module: "module_4",
        item_code: "PER16",
        question_text: "Managerii utilizează adaptat diferite metode de motivare în funcție de echipă.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Practică managerială matură", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER17",
        module: "module_4",
        item_code: "PER17",
        question_text: "Organizația măsoară periodic satisfacția angajaților.",
        options: [
          { label: "Nu măsurăm", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Sistematic cu follow-up", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER18",
        module: "module_4",
        item_code: "PER18",
        question_text: "Rezultatele privind satisfacția angajaților influențează deciziile manageriale.",
        options: [
          { label: "Nu influențează", value: 1 },
          { label: "Foarte puțin", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Decizii bazate pe feedback și date", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER19",
        module: "module_4",
        item_code: "PER19",
        question_text: "Promovările sunt bazate predominant pe performanță și competență.",
        options: [
          { label: "Predominant arbitrar", value: 1 },
          { label: "Mai degrabă subiectiv", value: 2 },
          { label: "Mixt", value: 3 },
          { label: "Predominant meritocratic", value: 4 },
          { label: "Proces formal și transparent", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "PER20",
        module: "module_4",
        item_code: "PER20",
        question_text: "Angajații percep corectitudine în evaluare și recompensare.",
        options: [
          { label: "Percepție negativă puternică", value: 1 },
          { label: "Nemulțumiri frecvente", value: 2 },
          { label: "Percepție mixtă", value: 3 },
          { label: "Majoritar pozitivă", value: 4 },
          { label: "Nivel ridicat de încredere și fairness", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_5",
    name: "Learning & Development",
    weight: 15,
    questions: [
      {
        id: "LND1",
        module: "module_5",
        item_code: "LND1",
        question_text: "Organizația are o abordare structurată privind dezvoltarea profesională a angajaților.",
        options: [
          { label: "Nu există abordare clară", value: 1 },
          { label: "Acțiuni punctuale, reactive", value: 2 },
          { label: "Inițiative parțial structurate", value: 3 },
          { label: "Plan coerent de dezvoltare", value: 4 },
          { label: "Strategie formală de learning & development", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND2",
        module: "module_5",
        item_code: "LND2",
        question_text: "Există obiective clare privind dezvoltarea competențelor angajaților.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte informal", value: 2 },
          { label: "Pentru anumite categorii", value: 3 },
          { label: "Clar definite pentru majoritatea angajaților", value: 4 },
          { label: "Integrate în strategia organizației", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND3",
        module: "module_5",
        item_code: "LND3",
        question_text: "Bugetul pentru training și dezvoltare este planificat anual.",
        options: [
          { label: "Nu există buget", value: 1 },
          { label: "Aprobare doar punctuală", value: 2 },
          { label: "Buget limitat informal", value: 3 },
          { label: "Buget anual dedicat", value: 4 },
          { label: "Buget strategic monitorizat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND4",
        module: "module_5",
        item_code: "LND4",
        question_text: "Nevoile de instruire sunt identificate printr-un proces formal.",
        options: [
          { label: "Nu sunt analizate", value: 1 },
          { label: "Decizii intuitive", value: 2 },
          { label: "Analiză ocazională", value: 3 },
          { label: "Analiză periodică structurată", value: 4 },
          { label: "Analiză continuă bazată pe date", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND5",
        module: "module_5",
        item_code: "LND5",
        question_text: "Managerii contribuie activ la identificarea nevoilor de dezvoltare ale echipelor lor.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Parte formală din management practice", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND6",
        module: "module_5",
        item_code: "LND6",
        question_text: "Rezultatele evaluării performanței sunt utilizate pentru definirea nevoilor de dezvoltare.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic și documentat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND7",
        module: "module_5",
        item_code: "LND7",
        question_text: "Angajații participă regulat la programe de formare profesională.",
        options: [
          { label: "Aproape deloc", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Parte normală a culturii organizaționale", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND8",
        module: "module_5",
        item_code: "LND8",
        question_text: "Organizația utilizează formate diverse de învățare (workshop, e-learning, mentoring).",
        options: [
          { label: "Un singur format", value: 1 },
          { label: "1–2 formate limitate", value: 2 },
          { label: "Câteva formate recurente", value: 3 },
          { label: "Minimum 4 formate", value: 4 },
          { label: "Ecosistem divers de învățare", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND9",
        module: "module_5",
        item_code: "LND9",
        question_text: "Organizația utilizează traineri interni pentru transfer de know-how.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Program formal de internal trainers", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND10",
        module: "module_5",
        item_code: "LND10",
        question_text: "Organizația utilizează expertiză externă pentru dezvoltarea angajaților.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Strategic și planificat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND11",
        module: "module_5",
        item_code: "LND11",
        question_text: "Învățarea continuă este încurajată activ în organizație.",
        options: [
          { label: "Nu este încurajată", value: 1 },
          { label: "Mesaje ocazionale", value: 2 },
          { label: "Sprijin limitat", value: 3 },
          { label: "Clar susținută", value: 4 },
          { label: "Parte a culturii organizaționale", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND12",
        module: "module_5",
        item_code: "LND12",
        question_text: "Angajații au acces facil la oportunități de învățare relevante.",
        options: [
          { label: "Acces foarte limitat", value: 1 },
          { label: "Acces dificil", value: 2 },
          { label: "Acces moderat", value: 3 },
          { label: "Acces bun", value: 4 },
          { label: "Acces facil și predictibil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND13",
        module: "module_5",
        item_code: "LND13",
        question_text: "Schimbul intern de cunoștințe este încurajat (knowledge sharing).",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Practică organizațională matură", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND14",
        module: "module_5",
        item_code: "LND14",
        question_text: "Managerii beneficiază de programe dedicate dezvoltării competențelor de leadership.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Program formal de leadership development", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND15",
        module: "module_5",
        item_code: "LND15",
        question_text: "Noii manageri primesc suport pentru tranziția în rol managerial.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Proces formal de management onboarding", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND16",
        module: "module_5",
        item_code: "LND16",
        question_text: "Angajații discută periodic despre dezvoltarea carierei lor în organizație.",
        options: [
          { label: "Niciodată", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Parte formală din people management", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND17",
        module: "module_5",
        item_code: "LND17",
        question_text: "Există oportunități interne de dezvoltare profesională sau mobilitate.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte limitate", value: 2 },
          { label: "Unele oportunități", value: 3 },
          { label: "Frecvente", value: 4 },
          { label: "Sistem clar de career development", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND18",
        module: "module_5",
        item_code: "LND18",
        question_text: "Impactul programelor de formare este evaluat.",
        options: [
          { label: "Nu evaluăm", value: 1 },
          { label: "Feedback informal", value: 2 },
          { label: "Evaluare punctuală", value: 3 },
          { label: "Evaluare periodică", value: 4 },
          { label: "Evaluare structurată cu indicatori", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "LND19",
        module: "module_5",
        item_code: "LND19",
        question_text: "Organizația urmărește dacă noile competențe sunt aplicate efectiv în muncă.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_6",
    name: "Employee Experience & Retention",
    weight: 15,
    questions: [
      {
        id: "EXR1",
        module: "module_6",
        item_code: "EXR1",
        question_text: "Organizația măsoară periodic satisfacția sau engagement-ul angajaților.",
        options: [
          { label: "Nu măsurăm deloc", value: 1 },
          { label: "Foarte rar / informal", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Sistematic, cu instrumente dedicate", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR2",
        module: "module_6",
        item_code: "EXR2",
        question_text: "Rezultatele măsurării satisfacției angajaților conduc la acțiuni concrete de îmbunătățire.",
        options: [
          { label: "Nu există follow-up", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic și documentat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR3",
        module: "module_6",
        item_code: "EXR3",
        question_text: "Organizația colectează feedback informal și formal de la angajați despre experiența lor de lucru.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Parte integrată din cultura organizațională", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR4",
        module: "module_6",
        item_code: "EXR4",
        question_text: "Angajații au canale clare prin care își pot exprima opiniile, preocupările sau sugestiile.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte limitat", value: 2 },
          { label: "Unele canale", value: 3 },
          { label: "Canale clare și utilizate", value: 4 },
          { label: "Sistem structurat de employee voice", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR5",
        module: "module_6",
        item_code: "EXR5",
        question_text: "Comunicarea internă privind deciziile importante este clară și predictibilă.",
        options: [
          { label: "Foarte slabă", value: 1 },
          { label: "Inconsistentă", value: 2 },
          { label: "Moderată", value: 3 },
          { label: "Bună", value: 4 },
          { label: "Matură și bine structurată", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR6",
        module: "module_6",
        item_code: "EXR6",
        question_text: "Managerii ascultă activ feedback-ul echipelor și reacționează constructiv.",
        options: [
          { label: "Aproape niciodată", value: 1 },
          { label: "Rareori", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Practică managerială constantă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR7",
        module: "module_6",
        item_code: "EXR7",
        question_text: "Organizația implementează măsuri pentru susținerea wellbeing-ului angajaților (ex. flexibilitate, wellbeing initiatives, work-life balance, support services).",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Inițiative punctuale", value: 2 },
          { label: "Unele măsuri recurente", value: 3 },
          { label: "Program coerent", value: 4 },
          { label: "Strategie formală de wellbeing", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR8",
        module: "module_6",
        item_code: "EXR8",
        question_text: "Organizația monitorizează riscuri privind stresul, burnout-ul sau suprasolicitarea.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Doar când apar probleme", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Periodic", value: 4 },
          { label: "Sistematic și preventiv", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR9",
        module: "module_6",
        item_code: "EXR9",
        question_text: "Managerii sunt preocupați de echilibrul dintre performanță și sănătatea echipelor.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Parte din cultura managerială", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR10",
        module: "module_6",
        item_code: "EXR10",
        question_text: "Organizația monitorizează fluctuația de personal (turnover).",
        options: [
          { label: "Nu", value: 1 },
          { label: "Informal", value: 2 },
          { label: "Monitorizare de bază", value: 3 },
          { label: "Monitorizare periodică", value: 4 },
          { label: "KPI activ cu analiză cauzală", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR11",
        module: "module_6",
        item_code: "EXR11",
        question_text: "Există măsuri deliberate pentru reducerea fluctuației de personal.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Reacții punctuale", value: 2 },
          { label: "Unele inițiative", value: 3 },
          { label: "Program coerent", value: 4 },
          { label: "Strategie formală de retenție", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR12",
        module: "module_6",
        item_code: "EXR12",
        question_text: "Organizația identifică pozițiile / categoriile de personal cu risc ridicat de plecare.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Intuitiv", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Analiză periodică", value: 4 },
          { label: "Risk monitoring formal", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR13",
        module: "module_6",
        item_code: "EXR13",
        question_text: "Organizația realizează exit interviews atunci când angajații părăsesc compania.",
        options: [
          { label: "Niciodată", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Standard procedural", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR14",
        module: "module_6",
        item_code: "EXR14",
        question_text: "Datele colectate din exit interviews sunt analizate și utilizate pentru îmbunătățire.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic cu măsuri concrete", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR15",
        module: "module_6",
        item_code: "EXR15",
        question_text: "Organizația discută activ cu angajații-cheie despre motivele pentru care aleg să rămână sau să plece (stay interviews / retention dialogue).",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Practică formală", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR16",
        module: "module_6",
        item_code: "EXR16",
        question_text: "Există inițiative dedicate fidelizării angajaților valoroși (ex. career pathways, recognition, retention packages, flexibility, development opportunities).",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Inițiative punctuale", value: 2 },
          { label: "Unele măsuri recurente", value: 3 },
          { label: "Program clar", value: 4 },
          { label: "Strategie diferențiată de retenție", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR17",
        module: "module_6",
        item_code: "EXR17",
        question_text: "Angajații au posibilitatea de dezvoltare sau mobilitate internă înainte de a căuta oportunități externe.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Politică formală de mobilitate internă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "EXR18",
        module: "module_6",
        item_code: "EXR18",
        question_text: "Angajații percep că organizația oferă perspective de evoluție profesională.",
        options: [
          { label: "Percepție negativă puternică", value: 1 },
          { label: "Perspective limitate", value: 2 },
          { label: "Percepție mixtă", value: 3 },
          { label: "Perspective clare", value: 4 },
          { label: "Perspective bine comunicate și susținute", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_7",
    name: "HR Digitalization",
    weight: 15,
    questions: [
      {
        id: "DIG1",
        module: "module_7",
        item_code: "DIG1",
        question_text: "Organizația utilizează un sistem digital dedicat pentru administrarea datelor de personal (ex. HR software, ERP HR module, HRIS, payroll-integrated systems).",
        options: [
          { label: "Exclusiv hârtie / Excel dispersat", value: 1 },
          { label: "Excel / fișiere locale limitate", value: 2 },
          { label: "Soluții digitale parțiale", value: 3 },
          { label: "Sistem digital utilizat pentru majoritatea datelor HR", value: 4 },
          { label: "Platformă HR integrată și centralizată", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG2",
        module: "module_7",
        item_code: "DIG2",
        question_text: "Datele despre angajați sunt actualizate, centralizate și ușor accesibile persoanelor autorizate.",
        options: [
          { label: "Foarte dispersate", value: 1 },
          { label: "Acces dificil", value: 2 },
          { label: "Parțial centralizate", value: 3 },
          { label: "Bună centralizare", value: 4 },
          { label: "Management matur al datelor HR", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG3",
        module: "module_7",
        item_code: "DIG3",
        question_text: "Documentele HR sunt gestionate digital (ex. contracte, acte adiționale, evaluări, training records, documente administrative).",
        options: [
          { label: "Exclusiv pe hârtie", value: 1 },
          { label: "Predominant hârtie", value: 2 },
          { label: "Mix hârtie + digital", value: 3 },
          { label: "Predominant digital", value: 4 },
          { label: "Flux complet digital document management", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG4",
        module: "module_7",
        item_code: "DIG4",
        question_text: "Procesele administrative HR sunt automatizate parțial sau complet (ex. leave requests, approvals, document generation, notifications).",
        options: [
          { label: "Exclusiv manual", value: 1 },
          { label: "Foarte puțin automatizat", value: 2 },
          { label: "Automatizare limitată", value: 3 },
          { label: "Mai multe procese automatizate", value: 4 },
          { label: "Automatizare matură a workflow-urilor", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG5",
        module: "module_7",
        item_code: "DIG5",
        question_text: "Procesele repetitive HR consumatoare de timp au fost simplificate sau digitalizate.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte puțin", value: 2 },
          { label: "Unele procese", value: 3 },
          { label: "Majoritatea proceselor repetitive", value: 4 },
          { label: "Optimizare continuă a proceselor", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG6",
        module: "module_7",
        item_code: "DIG6",
        question_text: "Angajații au acces digital la informații sau servicii HR fără intervenție manuală (ex. cereri concediu, adeverințe, actualizare date personale, documente).",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte limitat", value: 2 },
          { label: "Unele funcționalități", value: 3 },
          { label: "Multiple servicii disponibile", value: 4 },
          { label: "Self-service matur și utilizat activ", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG7",
        module: "module_7",
        item_code: "DIG7",
        question_text: "Managerii au acces la informații relevante despre echipele lor prin instrumente digitale.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Acces foarte limitat", value: 2 },
          { label: "Acces parțial", value: 3 },
          { label: "Acces bon", value: 4 },
          { label: "Dashboard managerial dedicat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG8",
        module: "module_7",
        item_code: "DIG8",
        question_text: "Organizația utilizează rapoarte digitale pentru monitorizarea indicatorilor HR (ex. turnover, absenteeism, recruitment metrics, training participation).",
        options: [
          { label: "Nu utilizăm", value: 1 },
          { label: "Rapoarte manuale rare", value: 2 },
          { label: "Rapoarte periodice de bază", value: 3 },
          { label: "Reporting structurat", value: 4 },
          { label: "Dashboard activ și utilizat în decizii", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG9",
        module: "module_7",
        item_code: "DIG9",
        question_text: "Datele HR sunt utilizate pentru luarea deciziilor manageriale.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Data-driven people decisions", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG10",
        module: "module_7",
        item_code: "DIG10",
        question_text: "Organizația poate genera rapid rapoarte relevante despre personal.",
        options: [
          { label: "Foarte dificil", value: 1 },
          { label: "Consum mare de timp", value: 2 },
          { label: "Posibil cu efort moderat", value: 3 },
          { label: "Rapid", value: 4 },
          { label: "Instant / dashboard live", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG11",
        module: "module_7",
        item_code: "DIG11",
        question_text: "Organizația utilizează instrumente digitale pentru training și dezvoltare (ex. e-learning, webinar, LMS, learning platforms).",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Ecosistem digital de learning", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG12",
        module: "module_7",
        item_code: "DIG12",
        question_text: "Comunicarea internă utilizează instrumente digitale moderne (ex. Teams, Slack, portals, digital announcements, employee apps).",
        options: [
          { label: "Foarte limitat", value: 1 },
          { label: "Utilizare minimă", value: 2 },
          { label: "Utilizare moderată", value: 3 },
          { label: "Utilizare activă", value: 4 },
          { label: "Parte integrată din employee experience", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG13",
        module: "module_7",
        item_code: "DIG13",
        question_text: "Datele HR sunt gestionate cu măsuri clare de securitate și control acces.",
        options: [
          { label: "Măsuri inexistente", value: 1 },
          { label: "Măsuri minimale", value: 2 },
          { label: "Control parțial", value: 3 },
          { label: "Măsuri clare aplicate", value: 4 },
          { label: "Standard matur de data governance", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG14",
        module: "module_7",
        item_code: "DIG14",
        question_text: "Organizația respectă cerințele GDPR privind datele angajaților.",
        options: [
          { label: "Nu există claritate", value: 1 },
          { label: "Respectare parțială", value: 2 },
          { label: "Conformitate de bază", value: 3 },
          { label: "Conformitate clara și documentată", value: 4 },
          { label: "Management matur de compliance digital", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG15",
        module: "module_7",
        item_code: "DIG15",
        question_text: "Funcția HR este deschisă către adoptarea de noi tehnologii și digitalizare.",
        options: [
          { label: "Rezistență puternică", value: 1 },
          { label: "Reticență ridicată", value: 2 },
          { label: "Deschidere moderată", value: 3 },
          { label: "Atitudine pozitivă", value: 4 },
          { label: "Proactivitate în inovare digitală", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "DIG16",
        module: "module_7",
        item_code: "DIG16",
        question_text: "Organizația investește în modernizarea digitală a proceselor HR.",
        options: [
          { label: "Nu investește", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Investiții punctuale", value: 3 },
          { label: "Investiții recurente", value: 4 },
          { label: "Strategie activă de digital transformation", value: 5 },
        ],
        weight: 1,
      },
    ]
  },
  {
    id: "module_8",
    name: "Compliance & HR Risk Management",
    weight: 15,
    questions: [
      {
        id: "COM1",
        module: "module_8",
        item_code: "COM1",
        question_text: "Documentele obligatorii privind relațiile de muncă sunt complete, actualizate și ușor accesibile (ex. contracte individuale de muncă, acte adiționale, fișe de post, decizii relevante).",
        options: [
          { label: "Documentație incompletă / neorganizată", value: 1 },
          { label: "Există lacune semnificative", value: 2 },
          { label: "Documentație parțial conformă", value: 3 },
          { label: "Documentație completă și bine organizată", value: 4 },
          { label: "Sistem matur, auditabil și actualizat constant", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM2",
        module: "module_8",
        item_code: "COM2",
        question_text: "Fișele de post sunt utilizate activ ca document managerial, nu doar formal.",
        options: [
          { label: "Lipsesc sau sunt pur formale", value: 1 },
          { label: "Rareori utilizate", value: 2 },
          { label: "Utilizare ocazională", value: 3 },
          { label: "Utilizare frecventă", value: 4 },
          { label: "Integrate în recrutare, evaluare și dezvoltare", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM3",
        module: "module_8",
        item_code: "COM3",
        question_text: "Organizația gestionează corect și la timp modificările contractuale (ex. funcție, salariu, program, responsabilități).",
        options: [
          { label: "Frecvente întârzieri / erori", value: 1 },
          { label: "Probleme recurente", value: 2 },
          { label: "Gestionare acceptabilă", value: 3 },
          { label: "Gestionare bună și predictibilă", value: 4 },
          { label: "Proces matur și controlat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM4",
        module: "module_8",
        item_code: "COM4",
        question_text: "Organizația urmărește activ modificările legislației muncii relevante.",
        options: [
          { label: "Nu există monitorizare", value: 1 },
          { label: "Reacție doar când apar probleme", value: 2 },
          { label: "Monitorizare ocazională", value: 3 },
          { label: "Monitorizare periodică", value: 4 },
          { label: "Proces formal de compliance monitoring", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM5",
        module: "module_8",
        item_code: "COM5",
        question_text: "Politicile și practicile HR sunt actualizate conform cerințelor legale.",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Sistematic și documentat", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM6",
        module: "module_8",
        item_code: "COM6",
        question_text: "Există suport intern sau extern pentru interpretarea aspectelor juridice de HR.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte limitat", value: 2 },
          { label: "Ocazional", value: 3 },
          { label: "Accees regulat", value: 4 },
          { label: "Suport clar și predictibil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM7",
        module: "module_8",
        item_code: "COM7",
        question_text: "Organizația are proceduri clare pentru gestionarea situațiilor disciplinare.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte neclare", value: 2 },
          { label: "Parțial definite", value: 3 },
          { label: "Clar definite și utilizabile", value: 4 },
          { label: "Formalizate și aplicate consecvent", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM8",
        module: "module_8",
        item_code: "COM8",
        question_text: "Managerii cunosc regulile și pașii privind gestionarea situațiilor disciplinare sau conflictelor de muncă.",
        options: [
          { label: "Nu cunosc", value: 1 },
          { label: "Cunoștințe foarte limitate", value: 2 },
          { label: "Cunoștințe moderate", value: 3 },
          { label: "Nivel bun de cunoaștere", value: 4 },
          { label: "Instruire formală și aplicare corectă", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM9",
        module: "module_8",
        item_code: "COM9",
        question_text: "Conflictele sau reclamațiile angajaților sunt gestionate prin mecanisme clare și echitabile.",
        options: [
          { label: "Nu există mecanisme clare", value: 1 },
          { label: "Gestionare ad-hoc", value: 2 },
          { label: "Unele practici", value: 3 },
          { label: "Proceduri clare", value: 4 },
          { label: "Sistem matur de employee relations", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM10",
        module: "module_8",
        item_code: "COM10",
        question_text: "Obligațiile privind sănătatea și securitatea în muncă (SSM) sunt gestionate conform cerințelor legale.",
        options: [
          { label: "Probleme majore", value: 1 },
          { label: "Lacune importante", value: 2 },
          { label: "Conformitate de bază", value: 3 },
          { label: "Bună conformitate", value: 4 },
          { label: "Sistem matur și preventiv", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM11",
        module: "module_8",
        item_code: "COM11",
        question_text: "Evaluările și instruirile obligatorii SSM sunt realizate la timp și documentate.",
        options: [
          { label: "Frecvente omisiuni", value: 1 },
          { label: "Probleme recurente", value: 2 },
          { label: "Acceptabil", value: 3 },
          { label: "Gestionare bună", value: 4 },
          { label: "Control matur și predictibil", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM12",
        module: "module_8",
        item_code: "COM12",
        question_text: "Organizația gestionează conform obligațiile privind medicina muncii.",
        options: [
          { label: "Probleme majore", value: 1 },
          { label: "Lacune importante", value: 2 },
          { label: "Conformitate minimă", value: 3 },
          { label: "Bună conformitate", value: 4 },
          { label: "Management matur și preventiv", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM13",
        module: "module_8",
        item_code: "COM13",
        question_text: "Organizația verifică periodic conformitatea documentelor și proceselor HR.",
        options: [
          { label: "Nu verificăm", value: 1 },
          { label: "Doar când apare o problemă", value: 2 },
          { label: "Verificări ocazionale", value: 3 },
          { label: "Verificări periodice", value: 4 },
          { label: "Audit intern formal HR", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM14",
        module: "module_8",
        item_code: "COM14",
        question_text: "Riscurile legate de resurse umane sunt identificate și discutate managerial (ex. litigii, turnover, absenteism, lipsă competențe, compliance failures).",
        options: [
          { label: "Nu", value: 1 },
          { label: "Foarte rar", value: 2 },
          { label: "Uneori", value: 3 },
          { label: "Frecvent", value: 4 },
          { label: "Parte formală din risk management", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM15",
        module: "module_8",
        item_code: "COM15",
        question_text: "Organizația are planuri sau măsuri preventive pentru reducerea riscurilor HR.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Măsuri reactive", value: 2 },
          { label: "Unele măsuri", value: 3 },
          { label: "Program coerent", value: 4 },
          { label: "Strategie preventivă matură", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM16",
        module: "module_8",
        item_code: "COM16",
        question_text: "Angajații au posibilitatea de a semnala probleme sau preocupări într-un mod sigur și clar.",
        options: [
          { label: "Nu există", value: 1 },
          { label: "Foarte limitat", value: 2 },
          { label: "Unele mecanisme", value: 3 },
          { label: "Canale clare", value: 4 },
          { label: "Sistem matur și de încredere", value: 5 },
        ],
        weight: 1,
      },
      {
        id: "COM17",
        module: "module_8",
        item_code: "COM17",
        question_text: "Organizația promovează tratament echitabil și decizii HR consistente.",
        options: [
          { label: "Frecvente percepții de inechitate", value: 1 },
          { label: "Probleme recurente", value: 2 },
          { label: "Situație mixtă", value: 3 },
          { label: "Percepție majoritar pozitivă", value: 4 },
          { label: "Standard ridicat de fairness", value: 5 },
        ],
        weight: 1,
      },
    ]
  }
];
